import mongoose from "mongoose";
import Document from "../models/files.js";
import dotenv from "dotenv";

dotenv.config();

const ownerAddress = "0xF8C85DddaAfE76E46593Cc565011716A31192B97";

const documentTypes = [
  "Passport",
  "Health",
  "License",
  "Certificate",
  "Finance"
];

const names = [
  "Digital Passport",
  "Medical record",
  "Driving License",
  "Degree Certificate",
  "Financial Statement"
];

const fileNames = [
  "passport_scan.pdf",
  "id_card_front.png",
  "driving_license.jpg",
  "degree_certificate.pdf",
  "property_deed.pdf"
];

const sizes = ["256 KB", "1.2 MB", "980 KB", "3.4 MB", "512 KB"];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI, { dbName: "SSI" });

    console.log("Connected to MongoDB");

    // Clear existing demo docs
    await Document.deleteMany({ ownerAddress });

    for (let i = 0; i < documentTypes.length; i++) {
      const doc = new Document({
        hash: `0x${(Math.random().toString(16) + "0".repeat(64)).slice(2, 66)}`,
        ipfsCid: `bafy${Math.random().toString(36).substring(2, 15)}`,
        ownerAddress,
        documentType: documentTypes[i],
        name: names[i],
        fileName: fileNames[i],
        size: sizes[i]
        // color will be auto-generated by the schema pre("save")
      });

      await doc.save();
    }

    console.log("✅ Demo documents inserted successfully");
    process.exit();
  } catch (err) {
    console.error("Error seeding documents:", err);
    process.exit(1);
  }
}

seed();
